name: Build WSA and Integrate Google Play Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip docker.io wget curl

      - name: Build WSA
        run: |
          cd WSA
          ./build.sh

      - name: Apply Magisk and OpenGApps (Optional)
        run: |
          ./apply_magisk_and_gapps.sh
